# Generated by Django 4.2.30 on 2026-06-27

from django.db import migrations, models
import django.db.models.deletion

def migrate_sales_to_items(apps, schema_editor):
    Sale = apps.get_model('api', 'Sale')
    SaleItem = apps.get_model('api', 'SaleItem')
    for sale in Sale.objects.all():
        # Get raw database row to access product_id and quantity fields
        # since they are removed from the reconstructed model class
        db_alias = schema_editor.connection.alias
        # Retrieve raw values using connection cursor or raw query to be safe
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("SELECT product_id, quantity FROM api_sale WHERE id = %s", [sale.id])
            row = cursor.fetchone()
            if row and row[0] is not None:
                product_id = row[0]
                quantity = row[1]
                SaleItem.objects.using(db_alias).create(
                    sale=sale,
                    product_id=product_id,
                    quantity=quantity,
                    brass=0.00,
                    rate=0.00,
                    amount=sale.sale_amount
                )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sale_amount_paid_sale_is_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Quantity sold')),
                ('brass', models.DecimalField(decimal_places=2, default=0.0, help_text='Quantity in brass', max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Price per unit', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount for this item', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='api.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.sale')),
            ],
        ),
        # Run the data migration to copy fields from Sale to SaleItem
        migrations.RunPython(migrate_sales_to_items, reverse_code=migrations.RunPython.noop),
        # Remove old fields from Sale model
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
    ]
