# Generated by Django 4.2.30 on 2026-06-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sale_multi_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company/Bank name', max_length=150)),
                ('loan_amount', models.DecimalField(decimal_places=2, help_text='Total loan amount', max_digits=12)),
                ('installment_amount', models.DecimalField(decimal_places=2, help_text='Installment (Hafta) amount', max_digits=12)),
                ('loan_date', models.DateField(help_text='Date when loan was taken')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-loan_date', '-created_at'],
            },
        ),
    ]
