# Generated by Django 4.2.30 on 2026-06-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='vehicle_no',
            field=models.CharField(blank=True, help_text='Vehicle / Truck number for dispatch', max_length=50, null=True),
        ),
    ]
