# Generated by Django 4.2.30 on 2026-06-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_saleitem_vehicle_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='production',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity produced (in Brass)', max_digits=10),
        ),
    ]
